name: Build files

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: git submodule update --recursive --init
      
      - uses: actions/checkout@v4
      - name: Make
        run: sh scripts/${{matrix.os}}/run.sh
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: out