name: Build files

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: actions/checkout@v4
      - name: Build files
        run: python run.py
    
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
            name: ${{matrix.os}}-output
            path: build
        